language: java
jdk:
- openjdk7
env:
  global:
  - TERM=dumb
  - secure: M3SLBuWnCedBfuywGZpiELk2D9Bc3e/hJ92cneulR+ZkcR/g1vTgZG4TwmESb5QrEwtyeeG/ByxDWvXXh1Yxo3P+Ixa47uxZX9qBStjiIZ2s8KDoFqwkLmhIxfZW3yHY26X/OuADaRtfpguHVEatoVS0Qj31jL+QZtJasVCdgB6BJmlThmzNWMtTLVebmnJNsxMV1fdNbGySvfDfoQfcAKBhvixDBqLIRX2E2mNyMB3mVJlGrsri2b89nwvfuxWrYA1ZgcnX5Yc+QFMdDg56NdWUKjUH7WGMfTj+mqZiSRArFwussjezO16+quFdd1TX9fmep59qA0v+83SUvXt2om3FPd5m2w0E3SexX9aD7TD43lcLzpt043uyDuE6ZfCf1UzTxT/Ps7F+kEunZEWFVSPks/GTefd2uFM6IvqKySRSpYFyua0DodhfVsjVT6cmFpelcC4N+SDiIlI769i0a5I0C1bzrkG2FZu6W2QdNWmvSQK01GIWQ9E7Vq6cae2hOjwME1sFRAGzYFMfR9HPfpChsR635QtM5q1iCh3jTn9Nj2Tkx7j14R2IK+zc4l+sUGLjz5pWVUoB9gCFNLOI3jwR1Iv9oaqKEVL5rOGMsD9bKrC5qXxfzHnP5yriQZiK1z/PPFaviEh62WJBaz0vAkUeUTH3h4rtJxDMkYNL26I=
  - secure: 1aJozqpPOEiLXSLtBRP73PFXWwAYnA+PJn8BL/Eu0UOuxXE+iRwUceAtJBwnPLPjnrDRTgCk8Eau5VV8NS4J2u/oLXVBbEXGOgS+YU+yp118+pgOPpp3rfxsR69qSnSehkiLGABnkmHO5K0BPQ/zSL77XItJ08+MUhkXU0Wjzy/SvJSP200am8hHMgaRdno7jwgdvR1QG9P56NmkF5IZwYgwPskcdUg2Auz4u2pm5RvGFdPIOV4IZDAfda5Qp7bqXz7Jcsobr6DEVrkrd/IzSVK+u29UpjFPYNK0Ce+MZ6eqbCn+ev9xqym15PGK/0kZ6tL3ekE9O/WkEv3jQd2gBHdYRYl031n+2AhJmLjHhnPSzcBMDhMBmx9Cvb4j7JM1IAsaUBF1Bl5iDQ1zID148RcyMRYNMXw/d/hZM405188WhPuBghRFAVsP2Nt07kW4UMfVcwRl5Vs1ZcAZqtFAjpehIk/aXMj3DKxyJElyCKFUlHfhxVQ43lXa5CRKHbeZ7DnMuZYxV+Kd9jt+eYzOajY0iOQUJEu87MdGd3M1VMK8isTulQ9VqE6hICgMNdGUuqv5YCJL/XWGLh6ZDNAwhM2wmB19KXBHlg3MarT/+dzo7ZCCSfnqGbakrJgTnJpMwV57JoYbi4NCFWNiL6M5UZksVzFK9J16DWKLub8+qkM=
notifications:
  email: false
sudo: false
after_success:
- scripts/travis-sonatype-publish.sh
