language: java
jdk:
- openjdk7
env:
  global:
  - TERM=dumb
  - secure: MIIQui0VS0HLvt+Qu0Ag3BV1ZLBCV2mF6mq7UfD9YEjj/0bsMEY4t4hQAOi5mLxvEQwNW+68tB/7DAEM8PCcfHOdCstSDTCjKbf6kuh5clrf+s8HbfTCHAOhNRuHULTz6LTLvIXHNOYKU4nUCcurXOqbU/5ncxU4UM53wGZUoXf/dxNybMtWQkFxG/tZ9hAZ9snJV9nZnUAgG4WLGBf+INrxgl8urm+AP4IxoUPoSg7AszX2T6CXc98/kBy+9EzxVH32vYXjbZyDoGAZN5FhdpcBcWi4s/dfNqAT0fj9vXeVs5mRiRKKhjoyBZfzXdpa92F3j7tsde2ciPa+BRWEYNcxN0wP6coLBDnzerZB5USiSsVxI1nuTnmsMQIAZ+U0YxnVzvb63uQlRJyVJwHM0FA5c0Gus7QN9OcpwXPQIqckhnrZ1qtS9S9m38/E6OoUfRxp9bjF6rSrzPLpsLSbc+k602z/+U1sZDOFu1OeRLWIkHmL+A4p+no6FMDkoJZ2g75mM4lzyVL8i/10lHm8X4PLgl+T5eJypWdGSdJQI8TM0hE7kFoIT79h43+2XnyScqS7H++h7ejVD8vgzdmglf4jzofuSEYpzK+gDJeXedjcg+lYzgUJ0g8JzwY3qPx2K6CEKsOKZ7a+KYIDeoKxE/MA1Ilk8BInm/cjJiNyooI=
  - secure: rZqjEfVYWH8tIWfjsBHOjieBdJKnsq6IGYT56vpFKlthZgdUuxo/k089y5UiNSOi2Wog4F59cTy+fhgd8qAHCFVkEu2Nqz28tU+huKlZIL077cIeVk0uPoV1P7HI7g7Ov+R0r+PpM2ClWnYPj/cQ3UQUB9YF0BS+LC+9yO9SQR1l1RYVoparw1CSP8ygd7Bdos6ZBG0T9Hf4a2rIuS5kY+wvHHz1Royga587TLsaBgrIvm2SZImuyLoY99Z5s+JnMNteASODnxRXau1/Vnz/zGVPK4AedOHVZW1BWIM7QPUUG/ycBh2stmdKZLQoMphV+XwFirZRBC9OLD01yXg7CzzceIFx2IdULu3ix/jL5gTvdU2RAYhtiMVPLePb9qSU3/uf7J3JqyZlsNLiC3QuJrGlUGzEYwsY90kOnjqMMdT6hGChYDT5nf7/kLyipnECl9paITCaBCeCLPk3oY5IcTAfEZlG6BRVtAf9MtLLFyOIv6ZVwhbDkQDemru8FyeqEDMzG4hGEao/oUVUsDj9GfQOx2wOQ7qxRZgNQnN8vPe24RE6l0tzqnMZ3uahvpZpwSpVGb0+YlXg2mVJuAVSkLgIq0iW5Bt9y7sJ1B6i3dWccJijwSTSK8V4RNsr+zLjrUJam2U55Aj58qATsJ1UJUxLCj+xsjhNDSZp9SrZes0=
notifications:
  email: false
sudo: false
after_success:
- scripts/travis-sonatype-publish.sh
