language: java

jdk:
  - openjdk7

env:
  global:
    - TERM=dumb
  secure: "vPcpmzg0JLmWswY5yS8CPtCBpTCIGCjJ9KdbSKF+RFzxxrS2JmSEa+te1bkEQt5Cz+H7JWNvIUvNaH83Vmt5rK0IbduJCZpFs/VeZUu4JAejcI4T4QVy5jbJlHDVPpMo3grzCsKpx6+zi0YVEdeZiCzGEir4F8oZeT7dJxLDBe5hRlmLx02xjuM+QkQW1xWddUCDyZ+hIzn1lgYNdRpPWCsn4aNs2IuKuZ1SYq3hdI2gcUh3gk6CY17XQ+HVa9vnWwwsZWeMoXlgL/a4SWEOevVw5i6pav3UHCmgBhLA69XZ9VvMX6P46/2MLUggCsi+kOhm9XL4hQg03wUa+5nmsanCms4ECG6H1yyOVQ4lpAUPmXSPYSHPSKn03uublg9sH0cNuKzWQ9vEqq9Q3CmwhHeIeQwp4v8UCH90dJdgiPq5xE0TbPf5GC6YsoRVo5kIsFIatNjoRP3p3H/1Hu6j9AFSsRhFdJy1jEvJYX374uoHkvA0e/X/o3P9k7otFdOcO3UVTVykZQLhnlgfI8R09o9eSLeogfk1O8pZXt3xj9pXAPR3LpgWM6ep51490LM196iux3dKd/5G46yGvSHorm/41rc4JK+MW9h8X8BaELHHnZN1frqYYhPfF4Bp8a9mKuiwH/sVg1zTa2LC9jIrFblhwIkWLjMISmMI94qFJkk="
  secure: "FlIIRVZQrLLNq5c6QITopLhfreIOLwRNJcXFQD4lLEzhEwlYprOTgVh2U9UmPQrE9gNyeV1GVgAKCwjC/ptUEafdWZRUqQtD3Uz/F/180w4ve5uhEztqgD5geM5m4u9vqQUSV+j6gmpX10deAzLsjkmNYkiKU4DlZQU7uspVjbK/+UoiWiaojCa4XdMBSQiI1YiH45AJxiGLP4jrVM0BwffDqQm4JAJnd3fgB6tLWviBPRxKq5TGedk2/OEYwAqQT+jel3t4bH/7M8sZj5rQrdQihDig9hYAeSeY1tSvDXxjoKrUbdrGExsS7io5oesjxIoCK0ryLZWyg4ZzODjPdDijdtuE5/AuLlhxmIl6rCuC+uMYizQco6gw35aa78V8l+0qDmE06zShdo1OVxSgchHvsZBcypIFv1yfoUKKROoGHlRcKaSYqTManzuuliBvgMxVBQAphiitZ7LW4kODHwK8NGh3SPmjl9VVncXl8zd9feJpmjqClDE4wNC41vwk2Nr5/h83akjYEhy5vxM1fBxMRIVdOD+8KAUX3mYWlJUHWnznwOOdcvVgDTzNlsw20Uehu08AQQR52uic1Rv7zCyW/5xsn+nkhDmrYzdo9n2Sjb5GM1TLdUheHPcngCwMVWg/xGG9tSFVyS5K1FhSG3nT+JkaKjMqYI1kAs1vk4A="

notifications:
  email: false

sudo: false

after_success:
  - scripts/travis-sonatype-publish.sh

