/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mitch' at '2016/01/02 3:22 PM' with Gradle 2.3
 *
 * @author mitch, @date 2016/01/02 3:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
